application:
    name: diy环境 @artifactId@
    version: diy环境 @version@
developer:
    name: diy环境 xkcoding
    website: diy环境 http://xkcoding.com
    qq: diy环境 237497819
    phone-number: diy环境 17326075631