server:
    port: 8086
    servlet:
        context-path: /examples
spring:
    data:
        mongodb:
            host: 43.135.50.171
            port: 27017
            database: article_db
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://43.135.50.171:3306/li_server?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
        username: root
        password: Logan@123
        driver-class-name: com.mysql.jdbc.Driver
        #    type: com.zaxxer.hikari.HikariDataSource
        initialization-mode: always
        continue-on-error: true
        #schema:
        #    - "classpath:db/schema.sql"
        #data:
        #    - "classpath:db/data.sql"
        hikari:
            minimum-idle: 5
            connection-test-query: SELECT 1 FROM DUAL
            maximum-pool-size: 20
            auto-commit: true
            idle-timeout: 30000
            pool-name: SpringBootDemoHikariCP
            max-lifetime: 60000
            connection-timeout: 30000
logging:
    level:
        com.xkcoding: debug
        com.xkcoding.orm.mybatis.mapper: trace
        org.springframework.data.mongodb.core: debug
mybatis:
    configuration:
        # 下划线转驼峰
        map-underscore-to-camel-case: true
    #  mapper文件映射地址
    mapper-locations: classpath:mappers/*.xml
    # mybatis 需要映射的实体类
    type-aliases-package: org.li.springboot_examples.entiry