### [POST] form-data uploadfiles and fields
# curl --location --request POST 'localhost:8086/api/param/form-data'
#--form 'name="jack"'
#--form 'id="30"'
#--form 'file=@"/Users/yunlong/Pictures/多啦Ameng.jpg"'
#--form 'file2=@"/Users/yunlong/Pictures/21121122112122.png"'
POST {{host}}/param/form-data
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

jack
--WebAppBoundary
Content-Disposition: form-data; name="id"

30
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="user.js"

./files/user.js
--WebAppBoundary
Content-Disposition: form-data; name="file2"; filename="user.js"

./files/user.js
--WebAppBoundary--







### [GET] path variables
GET {{host}}/param/path/somevar
Accept: application/json

### [GET] path query
GET {{host}}/param/query?name=jack
Accept: application/json

### [POST] body json
POST {{host}}/param/body
Content-Type: application/json

{
  "id": 1,
  "name": "jack"
}

### [POST] application/x-www-form-urlencoded
POST {{host}}/param/post-key
Content-Type: application/x-www-form-urlencoded

id=1&name='jack'

### [POST] application/x-www-form-urlencoded
POST {{host}}/param/post
Content-Type: application/x-www-form-urlencoded

id=1&name='jack'



### [post] form submit fields

POST {{host}}/param/form-data
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="id"

10

--WebAppBoundary
Content-Disposition: form-data; name="name"

jack
--WebAppBoundary--


