### 获取属性
GET http://localhost:8086/examples/property
Accept: application/json

### add mongodb
POST {{host}}/add
Content-Type: application/x-www-form-urlencoded
id=99&content=new-element

### path路径参数
GET {{host}}/param/path/jack1
Accept: application/json

### path query 参数
GET {{host}}/param/query?name=jack
Accept: application/json

### post text-body json
POST {{host}}/param/body
Content-Type: application/json

{
  "id":1,
  "name":"jack"
}

### post application/x-www-form-urlencoded
POST {{host}}/param/post
Content-Type: application/x-www-form-urlencoded

id=1&name='jack'

### post application/x-www-form-urlencoded object
POST {{host}}/param/postObject
Content-Type: application/x-www-form-urlencoded

id=1&name='jack'



### form-data提交(无文件)
POST {{host}}/param/form-data
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="my-data"

id-1
name-jack
--WebAppBoundary--

###